-- Generated by HyprMod

-- Settings
hl.config({
    misc = {
        force_default_wallpaper = 0,
    },
})

-- Workspaces
hl.workspace_rule({
    workspace = "3",
})
hl.workspace_rule({
    workspace = "2",
})
hl.workspace_rule({
    workspace = "1",
})
hl.workspace_rule({
    workspace = "1",
})

-- Keybinds
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.window.swap({ next = true }))
hl.unbind("SUPER + SHIFT + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill())

-- Window rules
hl.window_rule({
    name = "Workspace 1",
    match = {
        class = "^(Alacritty)$",
    },
    workspace = 1,
})
hl.window_rule({
    name = "Workspace 1",
    match = {
        class = "^(org\\.kde\\.dolphin)$",
    },
    workspace = 1,
})
hl.window_rule({
    name = "Workspace 2",
    match = {
        class = "^(zen)$",
    },
    workspace = 2,
})
hl.window_rule({
    name = "Workspace 3",
    match = {
        class = "^(md\\.obsidian\\.Obsidian)$",
    },
    workspace = 3,
})
